import type { ConsensusResponse } from "../types/consensus";

const reportTitle = "# AI Consensus Engine Report";
const limitationFooter = `---
Generated by AI Consensus Engine.

Consensus does not guarantee truth. Outputs may contain errors, omissions, or outdated information. Verify important claims independently.`;

export function buildConsensusMarkdown(
  result: ConsensusResponse,
  generatedAt = new Date(),
): string {
  return [
    reportTitle,
    "",
    "## Metadata",
    "",
    `- Generated At: ${formatGeneratedAt(generatedAt)}`,
    `- Primary Provider/Model: ${formatInlineValue(result.models_used.primary)}`,
    `- Reviewer Provider/Model: ${formatInlineValue(result.models_used.reviewer)}`,
    `- Synthesizer Provider/Model: ${formatInlineValue(result.models_used.synthesizer)}`,
    "",
    "## Question",
    "",
    formatBlockValue(result.question, "No question returned."),
    "",
    "## Final Consensus Answer",
    "",
    formatBlockValue(result.final_answer, "No final answer returned."),
    "",
    "## Agreement Points",
    "",
    formatList(result.agreement_points, "No agreement points returned."),
    "",
    "## Disagreement Points",
    "",
    formatList(result.disagreement_points, "No disagreement points returned."),
    "",
    "## Uncertainties / Caveats",
    "",
    formatList(result.uncertainties, "No uncertainties returned."),
    "",
    "## Suggested Follow-Up Questions",
    "",
    formatList(result.follow_up_questions, "No follow-up questions returned."),
    "",
    "## Primary Answer",
    "",
    formatBlockValue(result.primary_answer, "No primary answer returned."),
    "",
    "## Reviewer Critique",
    "",
    formatBlockValue(result.reviewer_critique, "No reviewer critique returned."),
    "",
    limitationFooter,
    "",
  ].join("\n");
}

export function buildMarkdownFilename(date = new Date()): string {
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  const seconds = pad(date.getSeconds());

  return `ai-consensus-report-${year}${month}${day}-${hours}${minutes}${seconds}.md`;
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = sanitizeFilename(filename);
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function formatGeneratedAt(date: Date): string {
  return date.toLocaleString();
}

function formatInlineValue(value: string): string {
  return sanitizeMarkdownText(value) || "Not returned";
}

function formatBlockValue(value: string, placeholder: string): string {
  return sanitizeMarkdownText(value) || placeholder;
}

function formatList(items: string[], placeholder: string): string {
  const safeItems = items.map(sanitizeMarkdownText).filter(Boolean);

  if (safeItems.length === 0) {
    return placeholder;
  }

  return safeItems.map((item) => `- ${item.replace(/\n/g, "\n  ")}`).join("\n");
}

function sanitizeMarkdownText(value: string): string {
  return value
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .trim();
}

function sanitizeFilename(filename: string): string {
  return filename.replace(/[^a-zA-Z0-9._-]/g, "-");
}

function pad(value: number): string {
  return value.toString().padStart(2, "0");
}
